version: "3.9"
   
services:
    db:
        image: bhumitech/my-mysql:1.0
        restart: always
        environment:
            MYSQL_DATABASE: 'novels'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'bhumit'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'admin123'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
    web:
        image: bhumitech/webnovel:1.0
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        depends_on:
        - db