version: "3.3"
   
services:
    db:
        image: bhumitech/my-mysql:1.0
        restart: always
        environment:
            MYSQL_DATABASE: 'novels'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3307:3306'
        security_opt:
            - seccomp:unconfined
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
    web:
        image: bhumitech/webnovel:2.0
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        depends_on:
        - db